- name: Configuring mysql server
  hosts: database
  become: true
  vars_files:
  - common_vars.yml
  - mysql_vars.yml
  vars:
    CMD_MYSQL_SET_PASS: "mysql_secure_installation --set-root-pass {{MYSQL_PASS}}"
  tasks:
  - name: Install PyMySQL for connecting to mysql server
    ansible.builtin.pip:
      name: "{{PIP_PKGS}}"

  - name: Installing mysql server
    ansible.builtin.dnf:
      name: "{{DNF_PKGS}}"
      state: present

  - name: Start and enable mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: true

  - name: Check if root password of mysql is set
    community.mysql.mysql_info:
      login_host: "{{MYSQL_DNS}}"
      login_user: "{{MYSQL_USER}}"
      login_password: "{{MYSQL_PASS}}"
    register: mysql_info
    ignore_errors: true

  - name: print mysql_info var output
    ansible.builtin.debug:
      msg: "{{mysql_info}}"

  - name: If root password not set, then set it
    ansible.builtin.command: "{{CMD_MYSQL_SET_PASS}}"
    when: mysql_info.failed is true
